Using phylolm to check PGLS with alternative models
===================================================



```{r}
#install package phylm
install.packages('phylolm')

```


```{r}

library(phylolm)
library(geiger)

```




```{r}


#load data
data <-read.table("./envPCsNohighCorrelated_and_morpho_matching_with_tree.csv", sep = ",", header = TRUE, row.names=1)  # env pca without high correlated vars
# data <-read.table("./envPCs_and_morpho_matching_with_tree.csv", sep = ",", header = TRUE, row.names=1) #env pca with all chelsa vars
tree <-read.tree("./RAxML_bipartitions.10-bolivia-initial_mcov0.25_rcov0")


#check correspondence
obj<-name.check(tree, data)
obj


#prune tree 
pruned_tree <- drop.tip(tree, obj$tree_not_data)

#check again correspondence
name.check(pruned_tree, data)


# Extract the row names as a separate column called ids
data$ids <- row.names(data)


# Extract relevant columns
subset_data <- data[, c("area", "env.pc2", "stellate_hairs_stalked")]


```


```
Original summary table in the analysis included in the paper

[1] "area ~ env.pc2"
               Value Std.Error  t-value      p-value
(Intercept) 18.81510 4.6421023 4.053142 0.0002138035
env.pc2      3.27077 0.9637309 3.393862 0.0015145184
```




```{r}

set.seed(88)

bm_model <- phylolm(area ~ env.pc2, data = subset_data, pruned_tree, model = "BM")


# Print model summary
summary(bm_model)




```

```{r}

set.seed(88)

bm_model <- phylolm(stellate_hairs_stalked ~ env.pc2, data = subset_data, pruned_tree, model = "BM")


# Print model summary
summary(bm_model)




```


```{r}

#exploring how to access the info I need from the phylolm object
      # summary_table <- summary(model)$tTable
      # results[i, j] <- summary_table[predictor_columns[j], "Value"]
      # pvalues[i, j] <- summary_table[predictor_columns[j], "p-value"]



summary(bm_model)$coefficients["env.pc2", "p.value"]
summary(bm_model)$coefficients["env.pc2", "Estimate"]

```



```{r}
library(phylolm)



ou_model <- phylolm(area ~ env.pc2, data = subset_data, pruned_tree, model = "OUrandomRoot")


# Print model summary
summary(ou_model)




```

```{r}
library(phylolm)



ou2_model <- phylolm(area ~ env.pc2, data = subset_data, pruned_tree, model = "OUfixedRoot")


# Print model summary
summary(ou2_model)




```


```{r}
library(phylolm)



eb_model <- phylolm(area ~ env.pc2, data = subset_data, pruned_tree, model = "EB",
       lower.bound = NULL, upper.bound = NULL,
       starting.value = NULL, measurement_error = FALSE,
       boot=0,full.matrix = TRUE)


# Print model summary
summary(eb_model)




```